server:
  port: 8072
build:
  version: "1.0"

bvr-auth:
  message: "Welcome to Bvr software auth service related local APIs "
  contactDetails:
    name: "Amaal Grega - Developer"
    email: "amaal@bvrsoftware.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bvr1?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
       initialization-fail-timeout: 60000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8071/eureka/

info:
  app:
    name: "bvr-auth"
    description: "Bvr software Auth Application"
    version: "1.0.0"

logging:
  level:
    com:
      bvr:
        BvrAuth: DEBUG