build:
  version: "1.0"

bvr-education:
  message: "Welcome to Bvr software education service related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@bvrsoftware.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/bvr1
