build:
  version: "1.0"

bvr-auth:
  message: "Welcome to Bvr software auth service related local APIs "
  contactDetails:
    name: "Amaal Grega - Developer"
    email: "amaal@bvrsoftware.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bvr1?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect