server:
  port: 8073
build:
  version: "1.0"

bvr-education:
  message: "Welcome to Bvr software education service related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@bvrsoftware.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/bvr1
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8071/eureka/

info:
  app:
    name: "bvr-education"
    description: "Bvr software Education Application"
    version: "1.0.0"
